### PR TITLE
Households

### LINKED ISSUE #13: Overview about household financials
# Card:

**Role:** User(s)
**Goal:** Show expenses / incomes of the shared household
**Reason:** Overview about the incomes and expenses of all people in the household

---

# Confirmation:

## Acceptance tests:

* Screen about household financials

### LINKED ISSUE #14: Create household
# Card:

**Role:** User / Household admin
**Goal:** Create a household
**Reason:** Share incomes / expenses between users

---

# Confirmation:

## Acceptance tests:

* UI (household name)
* Invite users
   * Create QR-Code to invite users

### LINKED ISSUE #15: Join household
# Card:

**Role:** User
**Goal:** Join a hosehold
**Reason:** share incomes / expenses between users

---

# Confirmation:

## Acceptance tests:

* UI for scanning invitation code
   * User is added to household

### PR DESCRIPTION
**Pull request by michael-mezgo**
- Households can be 
   - created
   - joined
   - left
- Financials can be added to households

closes #13 
closes #14 
closes #15 

Screenshot_20240618_223950
Screenshot_20240618_223937
Screenshot_20240618_223925
Screenshot_20240618_223912

### CODE REVIEW

**Comment by michael-mezgo** [comment]
@EP1210 @elimei1 pls test the PR on your devices / emulators to check if there are race conditions that do not occur on my system

**Comment by elimei1** [comment]
Great job. Just don't use it in dark mode, it still looks a bit weird.
Screenshot_20240619-182326

**Review by EP1210 — CHANGES_REQUESTED** [review]
# A few remarks

I tested this on the emulator since the app crashes on the real device:

- If I add a transaction to a household in the HouseholdTransactionAddScreen and then navigate back it seems that the transaction item is not immediately displayed in the HouseholdTransaction screen (also "Screen" is missing at the end of the name). The screen is successfully updated if a navigate to a different screen and then come back.
- The TransactionScreen and HouseholdTransactionAddScreen seem to be almost identical. Is it not possible to reuse the screen composable?

Apart from that it seems to be working fine.

**Comment by EP1210** [comment]
On the real device I get the same error that I already had once.

error

**Comment by michael-mezgo** [comment]
> Great job. Just don't use it in dark mode, it still looks a bit weird. !

@elimei1 thanks for your feedback :)
I've made some improvements in the dark mode
Screenshot_20240620_110341
Screenshot_20240620_110357

**Comment by michael-mezgo** [comment]
> On the real device I get the same error that I already had once.
> 
> error

Oh it seems that race conditions occur in the PR of @elimei #37. - Issue #16 
(I've merged your changes in my branch.)

**Comment by michael-mezgo** [comment]
> * The TransactionScreen and HouseholdTransactionAddScreen seem to be almost identical. Is it not possible to reuse the screen composable?

@EP1210 I think that some refactoring is needed here. But it's not easy: different ViewModels are provided and the HouseholdViewModel also has a path variable. (I think we could use path variables more often to get rid of the "big" view model. @EP1210 @elimei1.)
I'll make a note of this in #39.

**Comment by michael-mezgo** [comment]
> # A few remarks
> I tested this on the emulator since the app crashes on the real device:
> 
> * If I add a transaction to a household in the HouseholdTransactionAddScreen and then navigate back it seems that the transaction item is not immediately displayed in the HouseholdTransaction screen (also "Screen" is missing at the end of the name). The screen is successfully updated if a navigate to a different screen and then come back.
> * The TransactionScreen and HouseholdTransactionAddScreen seem to be almost identical. Is it not possible to reuse the screen composable?
> 
> Apart from that it seems to be working fine.

@EP1210 
https://github.com/EP1210/Budget_Fox/assets/58122000/dc0a3904-d320-494b-96c1-0cf76a5b9286

**Comment by michael-mezgo** [comment]
Commit ff958f615640a8daf3ab963be3ea504992863744 closes #16

**Review by EP1210 — APPROVED** [review]
Everything seems to work now 🙂

**Pull request merged**
