### PR TITLE
17 add saving goal

### LINKED ISSUE #17: Add saving goal
# Card:

**Role:** User
**Goal:** User wants to save money
**Reason:** The user would like to put money aside

---

# Confirmation:

## Acceptance tests:

* UI (name of the goal, amount)
* goal is added to the **user account** (not household)

### PR DESCRIPTION
**Pull request by michael-mezgo**
Saving goals can be added to user account 

Info:
Closes #17 
#18 and #20 will be committed in an extra branch

### CODE REVIEW

**Comment by EP1210** [comment]
I am sorry but the same error still remains even after the quick fix.

error

**Comment by elimei1** [comment]
@EP1210 which user did you choose (there are 3 Erik Pfandler in the database). One of them has still old transactions, without the isRegular field. If you used this user, I think you should delete all existing transactions before logging in.

**Comment by EP1210** [comment]
@elimei1 Deleting all transactions was the solution. Thank you. Though I have no idea where the other two clones suddenly came from :joy:.

**Comment by EP1210** [comment]
Adding a saving goal seems to work perfectly :+1:. Thank you.

**Review by EP1210 — APPROVED** [review]

**Comment by EP1210** [comment]
Something interesting that I observed just now is that firestore seems to have problems (I guess) if there are too many collections at a document. When I had saving goals and categories at my user document it did not seem to register my transactions anymore. I deleted the saving goal collection and then the transactions were back.

**Comment by michael-mezgo** [comment]
> @elimei1 Deleting all transactions was the solution. Thank you. Though I have no idea where the other two clones suddenly came from 😂.

@EP1210 it was my test data 😆

**Review by elimei1 — APPROVED** [review]
good job

**Comment by michael-mezgo** [comment]
Known issue: Error with ViewModel
Will be fixed in #44

**Comment by michael-mezgo** [comment]
Solved in 69e9e4a9

**Comment by michael-mezgo** [comment]
> Known issue: Error with ViewModel Will be fixed in #44

Solved in https://github.com/EP1210/Budget_Fox/commit/69e9e4a9cd6f1cfbc6696181cfdef3716921ade4

**Pull request merged**
